<!--Page des mentions légales.-->
<section class="section_mention">
    
    <article class="mention">


        <h2>LES MENTIONS LÉGALES</h2>
        <h3>- Mentions Légales - <i class="fa-solid fa-scale-balanced"></i></h3>

        <p>
            L’éditeur des sites Internet  Nawel'S Naturalia food -site.net est la société SARL dont le siège social est au 02 Rue Cornilliot 77400 Thorigny Sur Marne au capital de 150 000 euros immatriculée au Registre du commerce et des sociétés de SEINE ET MARNE sous le numéro RCS 531 550 217.

            N° de TVA intracommunautaire : FR 145 135 507 121

            Directeur de la publication : François DUPONT

            Tél. : 01 42 08 37 95

            Hébergement du site Internet Nawel'S Naturalia food -site.net réalisé par ONLINE.NET, 8, rue de la Ville , 77400 seine et marne. Tél. : +33 (0)1 84 13 00 00
        </p>


        <h3> - Cookies - </h3>
        <p>
            Finalité des Cookies Lors de votre consultation du site Nawel'S Naturalia food.fr, des informations relatives à votre navigation sont susceptibles d’être enregistrées dans des fichiers “Cookies” installés sur votre terminal (ordinateur, smartphone, tablette, etc.).

            Nous émettons ces cookies dans le but de faciliter votre navigation sur notre site. Ils peuvent également être émis par nos partenaires afin de personnaliser l’offre publicitaire qui vous est adressée en dehors du site Nawel'S Naturalia food -site.net

            Les cookies émis par Nawel'S Naturalia food -site.net
            Les cookies que nous installons nous permettent d’identifier votre navigateur lorsque vous vous connectez à notre site Nawel'S Naturalia food -site.net

            Soucieux d’apporter la meilleure offre de service possible aux utilisateurs du site Nawel'S Naturalia food -site.net, nous éditons des cookies pour :

            Établir des statistiques de fréquentation (nombre de visites, consultation des pages.. .),
            Optimiser la présentation de notre Site Nawel'S Naturalia food -site.net eût égard aux préférences d’affichage de votre terminal,
            Fournir à l’utilisateur du contenu en rapport avec ses centres d’intérêt et de personnaliser les offres qui lui sont adressées.

            Les Cookies émis par nos prestataires
            Lorsque vous consultez Nawel'S Naturalia food -site.net , des cookies édités par nos sociétés prestataires (cookies tiers) sont susceptibles d’être placés dans votre terminal via les pages de notre Site.

            Les cookies déposés par nos prestataires sur le site Nawel'S Naturalia food -site.net qui visent à promouvoir nos activités et nos offres, ont pour objet :

            D’identifier les produits consultés sur le site NAWEL'S restaurant -site.net afin de personnaliser l’offre publicitaire qui vous est adressée pour promouvoir des sites tiers (extérieur au site Nawel'S Naturalia food -site.net).
            De vous adresser des offres personnalisées par email, (uniquement si vous avez accepté de recevoir des offres de nos partenaires).
            De vous identifier sur notre espace fidélité
            L’émission et l’utilisation de cookies par nos prestataires sont soumises à leur politique de protection de la vie privée. Nawel'S Naturalia food -site.net n’a ni accès, ni contrôle sur leurs cookies. Toutefois Nawel'S Naturalia food -site.net veille à ce que ses prestataires traitent les informations collectées sur le Site Nawel'S Naturalia food -site.net exclusivement pour les besoins de Nawel'S Naturalia food.great-site.net et dans le respect de la loi « Informatique et Libertés ».
            Vous pouvez refuser les cookies tiers par un paramétrage appropriés de votre navigateur.

        </p>


        <h3> - Informatique et Libertés -</h3>
        <p>
            Le site NAWEL'S restaurant -site.net est déclaré sous le numéro 1878477 auprès de la Commission Nationale Informatique et Libertés (CNIL) en application de la loi n°78-17 du 6 janvier 1978 modifiée en 2004, relative à l’informatique, aux fichiers et aux libertés. Les informations recueillies font l’objet d’un traitement informatique destiné à la communication d’offres commerciales, d’informations sur les produits et la marque Maison B. Le destinataire des données est la société SARL NAWEL'S restaurant. Conformément à la loi « informatique et libertés », chaque internaute ayant déposé, sur le site NAWEL'S restaurant -site.net, des informations nominatives le concernant, bénéficie d’un droit d’accès et de rectification de ces données, qu’il peut exercer en s’adressant à la société : NAWEL'S restaurant :02 Rue Cornilliot 77400 ThorignySur Marne.
        </p>


        <h3>- Garantie et Sécurité -</h3>
        <p>
            Le contenu de ce site est édité sous réserve d’erreurs techniques et/ou typographiques et avec des photos non contractuelles. La responsabilité de la société SARL<strong> NAWEL'S restaurant</strong> ne saurait donc être engagée quant à l’exactitude des informations mises à disposition des utilisateurs qui accèdent au site. SARL <strong> NAWEL'S restaurant</strong> ne peut en outre garantir que son fonctionnement sera exempt d’interruptions ou d’erreurs.
        </p>
    </article>
</section>