<section class="valid_basket_formulaire formulaireInformation">

    <h2>Valider ma commande </h2>

    <aricle class="basket_formulaire">
        <label for="name" class="">Nom</label>
        <input type="text" name="name" placeholder="name">

        <label for="prenom" class="prenom">Prénom</label>
        <input type="text" name="prenom" placeholder="prenom">

        <label for="adresse" class="adresse">Adresse</label>
        <input type="text" name="adresse" placeholder="adresse">

        <label for="phone" class="phone">Numéro de téléphone</label>
        <input type="phone" name="phone" placeholder="phone">

        <label for="email" class="email">Email</label>
        <input type="mail" name="email" placeholder="email">

        <div class="card_pay">
            <img src="asset/images/logo_paiement.jpg" alt="photo pour carte bancaire">
        </div>

        <div class="button_formulaire">
            <a href="index.php?route=validBasket"  class="btn_information">Valider mon paiement</a>
            <a href="index.php?route=basket" class="btn_valid_basket">Retour au panier</a>
        </div>
    </aricle>
</section>