<!--Page pour ajouter les produits-->

<section class="section_add_products">

    <article class="add_products">
        <h2>Tableau des produits</h2>

        <form action="index.php?road=addNewProducts" method="POST" class="form_product">
            <fieldset>
                <legend> Ajouter produits</legend>
              
                <?php require_once('_errors.phtml'); ?>

                <div class="addprod_name">
                    <label for="name">Nom du produit</label>
                    <input type="name" name="prod_name" id="prod_name">
                </div>

                <div class="addprod_description">
                    <label for="name">Description</label>
                    <textarea name="prod_description" id="prod_description"></textarea>
                </div>
                <div class="addcategrie">
                    <label for="categrie">Catégorie du produit</label>
                    <select name="cat_name" id="cat_name">
                        <option selected>choisir catégorie</option>
                        <option value="1">1-Entrée</option>
                        <option value="2">2-Plat</option>
                        <option value="3">3-Déssert</option>
                        <option value="4">4-Boisson</option>
                    </select>
                </div>
                <div class="addprod_price">
                    <label for="name">Prix</label>
                    <input type="name" name="prod_price" id="prod_price" placeholder="Prix du  produit">
                </div>
                <div class="addprod_image">
                    <label for="fileUpload">Importer image</label>
                    <input type="file" id="fileUpload" name="prod_image">
                </div>

                <button type="submit">Ajouter</button>
               

            </fieldset>
        </form>

    </article>
</section>