<!--Tableau de gestion des utilisateurs.-->
<section class="section_users_admin">

    <article class="users_admin">

        <h2>Tableau des utilistateurs</h2>


        <div>
            <table class="tab_users">
                <thead>
                    <tr>
                        <th>Id-utilistateurs</th>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Email-d'utilisateur</th>
                        <th>date-création</th>

                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <!--récupérer et retourner un utilisateur. -->
                    <?php foreach ($users as $user) : ?>
                        <tr>
                            <td><?= htmlspecialchars($user['user_id']) ?></td>
                            <td><?= htmlspecialchars($user['user_lastname']) ?></td>
                            <td><?= htmlspecialchars($user['user_firstname']) ?></td>
                            <td><?= htmlspecialchars($user['user_email']) ?></td>
                            <td><?= htmlspecialchars($user['user_create_at']) ?></td>
                            <td><?= htmlspecialchars($user['user_role']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </article>
</section>